name: issue-598 & 599
on: push
  

jobs:
  my_first_job:
    if: "!always()"
    runs-on: ubuntu-latest
    steps:
      - name: My first false step
        if: "contains(github.event_name, 'pull_request')"
        uses: actions/hello-world-javascript-action@main
        with:
          who-to-greet: 'Mona the Octocat'
      - name: My first true step
        if: "!endsWith('Hello world', 'od')== Always()"
        uses: actions/hello-world-javascript-action@main
        with:
          who-to-greet: 'Mona the Octocats'
      - name: Check upvote
        uses: Renstrom/upvote@11f9e0d7f2b7f8432b840338b156f8074bd9a1b3
        with:
          repository: ${{github.repository}}
          label: "Course Automation"
          
           
